path_to_wine_git_folder="Z:/home/serhan/Shared/wine_git"

logging_enabled=0

auto_create_tmp_folder_if_missing=1

# When enabled and when there's some data piped (stdin) into git.exe, the
# process waits 150ms at max until the first 8 bytes are read and times out
# otherwise.
stdin_timeout_enabled=1
