<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <AssemblyName>git</AssemblyName>
    <Authors>Serhan Apaydın</Authors>
    <VersionPrefix>0.6.0</VersionPrefix>
    <PackageDir Condition="'$(PackageDir)' == ''">$([System.IO.Path]::Combine($(OutputPath), 'package'))/</PackageDir>
    <PackagePath Condition="'$(PackagePath)' == ''">$([System.IO.Path]::Combine($(PackageDir), 'wine_git.zip'))</PackagePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Ini" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <None Update="settings.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="worker.sh">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="Package" DependsOnTargets="Publish">
    <Exec Command="del /Q /S &quot;$(MSBuildProjectDirectory)/$(PublishDir)/*.pdb&quot;" />
    <MakeDir Directories="$(PublishDir)tmp" />
    <MakeDir Directories="$(PackageDir)" />
    <ZipDirectory Overwrite="true" SourceDirectory="$(MSBuildProjectDirectory)/$(PublishDir)" DestinationFile="$(PackagePath)" />
  </Target>

</Project>
